# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095bf1cd9cc28a3f165a1132ca9e61e296895759e4773046f16b03d7d5b1ed01e2705cbb50724ee6bbd7adc4d287bf3da02deaf285f1b8dcde3c8d1a29d5958a

test:
  secret_key_base: 30f24e6b8f56be5732b0cc25c031c619bcee315301baf4968d69b6e99369e920e739ac067b82e50e8af9c0c6d5dc1f6e95ce1e78fc9d8075f482ddbfd7f78c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
